version: '3.8'
services:
  db:
    image: postgis/postgis:14-3.3 # Official PostGIS image
    container_name: crime_db
    environment:
      - POSTGRES_USER=police_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=crime_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: